### ISSUE TITLE
ERROR: Site piapp does not exist!

### ISSUE THREAD

**Issue by Richard238** [naztronaut/FCW#1]
Hi, Getting this error:
```
pi@raspberrypi:/etc/apache2/sites-available $ sudo a2ensite piapp.conf
ERROR: Site piapp does not exist!


pi@raspberrypi:/etc/apache2/sites-available $ sudo a2dissite 000-default.conf
Site 000-default disabled.
To activate the new configuration, you need to run:
  systemctl reload apache2
pi@raspberrypi:/etc/apache2/sites-available $ sudo service apache2 restart
```

/var/www/piApp - Folder is empty.

Go to   <ip_addr>/fcw = Not Found

Go to  <ip_addr> = previous project, "Controlling an LED with your Browser"

Thank you.

**Comment by naztronaut** [comment]
Sorry that was a typo in the readme, it should have said `fcw.conf` and not `piapp.conf`. The configuration file is located here: https://github.com/naztronaut/FCW/blob/master/utils/apache-led.conf 

You can rename it to fcw.conf after you move that file over to `/etc/apache2/sites-available` and run `sudo a2ensite piapp.conf`. 

All the other files should be placed in `/var/www/html/fcw`. Let me know if placing the files correctly works. 

Apologies for skipping over a lot of steps, this was more of a demo and I covered the specific topics in-depth in my older tutorials: https://www.easyprogramming.net/raspberrypi.php

Tutorials 7-10 goes over all the specific details of everything I do in this one project. 

Let me know if you get stuck anywhere.

**Comment by Richard238** [comment]
I hadn't installed Apache, so everything's in `/home/pi/fcw`  
Is it OK to leave that there [and ignore it], install Apache, and then go to `/var/www/html/fcw/venv/bin/` and run the
`wget https://raw.githubusercontent.com/naztronaut/RaspberryPi-RGBW-Control/master/utils/activate_this.py`  ?

Thank you.

**Comment by Richard238** [comment]
**Error: Could not locate a Flask application.**

pi@raspberrypi:~ $ cd /var/www
pi@raspberrypi:/var/www $ sudo mkdir piapp
pi@raspberrypi:/var/www $ cd piapp
pi@raspberrypi:/var/www/piapp $ sudo apt install python3-venv
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-venv is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:/var/www/piapp $ sudo python3 -m venv venv
pi@raspberrypi:/var/www/piapp $ . venv/bin/activate
(venv) pi@raspberrypi:/var/www/piapp $ deactivate
pi@raspberrypi:/var/www/piapp $ sudo chown -R pi:pi venv
pi@raspberrypi:/var/www/piapp $ . venv/bin/activate
(venv) pi@raspberrypi:/var/www/piapp $ pip install flask
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting flask
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 1.4MB/s
Collecting click>=5.1 (from flask)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 2.0MB/s
Collecting Jinja2>=2.10.1 (from flask)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 1.3MB/s
Collecting itsdangerous>=0.24 (from flask)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.15 (from flask)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
    100% |████████████████████████████████| 307kB 800kB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp37-cp37m-linux_armv7l.whl
Installing collected packages: click, MarkupSafe, Jinja2, itsdangerous, Werkzeug, flask
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 click-7.1.2 flask-1.1.2 itsdangerous-1.1.0
(venv) pi@raspberrypi:/var/www/piapp $ sudo nano piapp.py
(venv) pi@raspberrypi:/var/www/piapp $ sudo nano piapp.py
(venv) pi@raspberrypi:/var/www/piapp $ flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
(venv) pi@raspberrypi:/var/www/piapp $

**Comment by Richard238** [comment]
Created   `(venv) pi@raspberrypi:/var/www $ sudo nano hello.py`
But cannot see it anywhere.

Flask - following these instructions...,
`https://projects.raspberrypi.org/en/projects/python-web-server-with-flask/1`
... flask works OK.

Apache - default homepage shows OK too.

**Comment by naztronaut** [comment]
Flask and Apache works now? Looks like you made a lot of progress since I last saw your response so I'm not sure where you're stuck right now. Are you still trying to get flask to run? 

The flask instructions you followed is good. I also have a set of steps here: https://www.easyprogramming.net/raspberrypi/pi_flask_app_server.php

Let me know where you're stuck right now. A screenshot of your directory setup would also be helpful so I can see where your venv and flask files are just to verify everything is right. If you already figured it out then awesome!

**Comment by Richard238** [comment]
File structure screenshots, as requested. 

![fcw2](https://user-images.githubusercontent.com/25931438/96714845-a9d2fc00-139a-11eb-8ffa-291238bdf77c.PNG)
![fcw1](https://user-images.githubusercontent.com/25931438/96714846-a9d2fc00-139a-11eb-9917-b8eb18e5a063.PNG)

Thanks for your help!

**Comment by Richard238** [comment]
File structure as requested, and browser showing both working OK.

![fcw4](https://user-images.githubusercontent.com/25931438/97027816-30cad480-1553-11eb-98d6-a9cb15376c14.PNG)
![fcw3](https://user-images.githubusercontent.com/25931438/97027818-30cad480-1553-11eb-8730-5a8cae3ef0ad.PNG)
![fcw5](https://user-images.githubusercontent.com/25931438/97027820-31636b00-1553-11eb-8ad6-03421818b3fe.PNG)


Thank you!

**Comment by naztronaut** [comment]
What's in your fcw folder? If all the files from this repo are there, you can run flask from there. The main file is called `led.py`  instead of `hello.py`. If you run that the same way you ran `hello.py`, you should be able to see the app in your browser.

**Comment by Richard238** [comment]
I think the populated fcw is in the wrong place.

Should this be run from /var/www/fcw ?
```
Here are some quick steps to take once you are inside your fcw folder:
sudo python3 -m venv venv
sudo chown -R pi:www-data venv
pip3 install flask
cd venv/bin/
wget https://raw.githubusercontent.com/naztronaut/RaspberryPi-RGBW-Control/master/utils/activate_this.py
```

**/home/pi/fcw Has all the files from your repo.**

![fcw6](https://user-images.githubusercontent.com/25931438/97081082-fd8e5100-15f7-11eb-913b-8012118ca62a.PNG)

**/var/www/fcw Has not many files at all.** 

![fcw7](https://user-images.githubusercontent.com/25931438/97081081-fcf5ba80-15f7-11eb-941e-ce309b779bde.PNG)

Thanks for your help! :)

**Comment by naztronaut** [comment]
Yes! Those are the correct steps. Before you run 'pip3 install flask`, you should activate your virtual environment:

```
. venv/bin/activate
```

This way when you run `pip3 install flask` it's in the virtual environment. It's a miss on my part, I just updated the README to include that step.  

it's fine if you don't do it in a venv, Flask will be installed globally and that's totally fine as well. 

Good luck! Let me know if you stuck anywhere.

**Comment by Richard238** [comment]
Still not working :(

I started here:   /var/www/fcw

sudo python3 -m venv venv
sudo chown -R pi:www-data venv
. venv/bin/activate
pip3 install flask
cd venv/bin/
wget https://raw.githubusercontent.com/naztronaut/RaspberryPi-RGBW-Control/master/utils/activate_this.py


`
```
pi@raspberrypi:~ $ cd /var/www/fcw
pi@raspberrypi:/var/www/fcw $ sudo python3 -m venv venv
pi@raspberrypi:/var/www/fcw $ sudo chown -R pi:www-data venv
pi@raspberrypi:/var/www/fcw $ . venv/bin/activate
(venv) pi@raspberrypi:/var/www/fcw $ pip3 install flask
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting flask
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from flask)
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting click>=5.1 (from flask)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from flask)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting Werkzeug>=0.15 (from flask)
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask)
  Using cached https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp37-cp37m-linux_armv7l.whl
Installing collected packages: itsdangerous, click, MarkupSafe, Jinja2, Werkzeug, flask
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 click-7.1.2 flask-1.1.2 itsdangerous-1.1.0
(venv) pi@raspberrypi:/var/www/fcw $ cd venv/bin/
(venv) pi@raspberrypi:/var/www/fcw/venv/bin $ wget https://raw.githubusercontent.com/naztronaut/RaspberryPi-RGBW-Control/master/utils/activate_this.py
--2020-10-29 15:59:07--  https://raw.githubusercontent.com/naztronaut/RaspberryPi-RGBW-Control/master/utils/activate_this.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.0.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1517 (1.5K) [text/plain]
Saving to: ‘activate_this.py.1’

activate_this.py.1  100%[===================>]   1.48K  --.-KB/s    in 0s

2020-10-29 15:59:07 (4.09 MB/s) - ‘activate_this.py.1’ saved [1517/1517]

(venv) pi@raspberrypi:/var/www/fcw/venv/bin $



(venv) pi@raspberrypi:/var/www/fcw/venv/bin $ cd
(venv) pi@raspberrypi:~ $ cd /etc/apache2/sites-available
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo nano fcw.conf
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo a2ensite piapp.conf
Site piapp already enabled
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo a2dissite 000-default.conf
Site 000-default already disabled
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo service apache2 restart
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo a2ensite fcw.conf     Enabling site fcw.
To activate the new configuration, you need to run:
  systemctl reload apache2
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo a2dissite 000-default.conf
Site 000-default already disabled
(venv) pi@raspberrypi:/etc/apache2/sites-available $ sudo service apache2 restart
```


http://192.168.1.11/ = Apache2 default page.



![fcw8](https://user-images.githubusercontent.com/25931438/97601997-b1ca1600-1a02-11eb-8cab-fb33a8b040ab.PNG)
![fcw9](https://user-images.githubusercontent.com/25931438/97601989-b098e900-1a02-11eb-8061-864a635e9608.PNG)
![fcw10](https://user-images.githubusercontent.com/25931438/97601990-b098e900-1a02-11eb-8040-cee7e38002fa.PNG)
![fcw11](https://user-images.githubusercontent.com/25931438/97601993-b1317f80-1a02-11eb-9362-7bad22f0ecb9.PNG)

**Comment by naztronaut** [comment]
In your .conf file, you have the path to fcw as `/var/www/**html**/fcw/` but in your directory structure it's in `/var/www/fcw`. 

Can you move everything in the 'fcw' folder to inside the html folder OR modify `fcw.conf` so that the path is correct? The latter may be easier to do. 

Once you have that done, restart apache and try again. 

If it still doesn't work, try  disabling the other configurations like this:

```
sudo a2dissite piapp.conf
```

Disable everything but `fcw.conf`, restart apache, and try again.

**Comment by Richard238** [comment]
I tried it with /html/ removed from fcw.conf. 
That made no difference.

I then moved the fcw folder....., 
`
pi@raspberrypi:~ $ sudo mv /var/www/fcw /var/www/html
`
.....and put the /html/ back in the fcw.conf 

It now loos like this:
![image](https://user-images.githubusercontent.com/25931438/97702499-ff985a00-1aa6-11eb-92b6-1a3b1c5a14e9.png)

And the default page still works, so Apache is happy, it just can't find the /fcw
![image](https://user-images.githubusercontent.com/25931438/97702719-5aca4c80-1aa7-11eb-9af6-e6b0ec45b8a2.png)

**Comment by naztronaut** [comment]
Have you tried disabling the other configurations? I wonder if one of t hem is interfering with this set up. 

It could be piapp that's interfering. So try disabling that if you haven't:

```
sudo a2dissite piapp.conf
```

Then enable fcw:

```
sudo a2ensite fcw.conf
```

Then restart apache:
```
sudo service apache2 restart
```

**Comment by Richard238** [comment]
Good idea, but sadly not the fix!
```
pi@raspberrypi:~ $ sudo a2dissite piapp.conf
Site piapp already disabled
pi@raspberrypi:~ $ sudo service apache2 restart
pi@raspberrypi:~ $ sudo a2ensite fcw.conf
Site fcw already enabled
pi@raspberrypi:~ $
```
Still shows 404 not found

**Comment by naztronaut** [comment]
Very strange. It worked for piapp though right? Just not fcw? 

Do you have fcw.wsgi in your fcw directory? Or is it still led.wsgi? Looking at your screenshot here:

![image](https://user-images.githubusercontent.com/8021112/97786613-1f9d4b80-1b83-11eb-9f33-448e5720ae3f.png)

If it's still led.wsgi, rename it. 

I need to rename the files in my repo more consistently. This is what happens when I work on multiple projects in the same Pi, I have to adjust things as I go.

**Comment by Richard238** [comment]
Before I forget, let me just say thank you for all your help with this, I'm sure we can fix it! :-)

I understand the naming thing, I'm forever adjusting things in a hurry, using rubbish names, and not documenting anything.
Come back to it ages later when it breaks or needs  a change applied, and not have a clue what I was doing.
Actually documentation is getting better, a new folder for each Pi project on my NAS, with a READ_ME.txt containing links, notes etc certainly helps a lot.

OK!
Switched Pi on, renamed `led.wsgi` to `fcw.wsgi ` and restarted apache2

![image](https://user-images.githubusercontent.com/25931438/97802701-37d1a100-1c3d-11eb-9e38-ead52357ff66.png)



And for good measure, here's what's in _fcw.wsgi_


![image](https://user-images.githubusercontent.com/25931438/97802789-d0682100-1c3d-11eb-9ad3-ed10d83cc1e1.png)


Noticed I'm not in the venv, is that correct?

Tried this, but didn't fix it.
![image](https://user-images.githubusercontent.com/25931438/97803057-9f88eb80-1c3f-11eb-9931-67a9472eda3c.png)

**Comment by naztronaut** [comment]
No problem! Happy to help. I'm sure we'll figure it out too, I'm sure it's just a small configuration thing somewhere. 

Can you look at your error log and see what it says. It should be located in `/var/log/apache2/error.log`. 

You can also see the access logs there to see what it says `/var/log/apache2/access.log`. 

If you use apache, you don't have to be in your venv. Just out of curiosity, if you're in your venv, can you run flask and does fcw work then?  `flask run --host=0.0.0.0` - and can you access it?

**Comment by Richard238** [comment]
Access log is empty
Error log shows:
`[Mon Nov 02 14:21:30.960416 2020] [wsgi:error] [pid 1392:tid 1913619488] [client 192.168.1.2:53310] Target WSGI script not found or unable to stat: /var/www/html/fcw/fcw.wsgi`

Checked that directory, it's not there.

`fcw.wsgi` is in `/home/pi/fcw`

**Comment by naztronaut** [comment]
I think I missed that. Do you have fcw in both /home/pi _and_ /var/www/html? In your previous screenshot, it's in /home/pi/fcw but the screenshot from a few days ago is in /var/www/html/fcw so I think I didn't pay close enough attention to the directory structures before and copied/pasted the wrong screenshot. Sorry about that.

It should be in /var/www/html. You should move the entire directory in there and restart apache. Apache can only do things inside the /var/www directory.

**Comment by Richard238** [comment]
Success!

A few issues along the way
_[Tue Nov 03 16:44:04.071242 2020] [wsgi:error] [pid 3359:tid 1948341280] [remote 192.168.1.2:54925] FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/fcw/venv/bin/activate_this.py'_

Found `activate_this.py` elsewhere and copied it in to `/var/www/html/fcw/venv/bin`

I have [this for the LEDs](https://www.amazon.co.uk/Adafruit-NeoPixel-Jewel-Integrated-Drivers/dp/B00Q9R8QUO/ref=sr_1_9?dchild=1&keywords=neopixel&qid=1604424060&sr=8-9)   (I have changed the conf file to reflect the quantity of LEDs in use.)
They're on another Pi running well, I'll move them to this Pi when i get chance, just super busy WFH and everything else just now.
Once I know that works, I'll buy more neopixels!

Thanks again for all your help with this.

![image](https://user-images.githubusercontent.com/25931438/98018549-955e1d00-1df8-11eb-9833-e28679b2a83c.png)

**Comment by naztronaut** [comment]
Awesome! Glad you have it working and I'll be here if you have more questions. 

Have fun!

**Comment by Richard238** [comment]
Just wondering, as I now have files and folders all over the place.
Make a clean start.

Backup  `var/www/html/fcw`
Reformat the SD card and re-write the OS
Install Apache
Put the backup of fcw   back into `var/www/html/fcw`
Run   `wget https://raw.githubusercontent.com/naztronaut/RaspberryPi.....`   from ` var/www/html/fcw`
(I'm not worried about using Flask and venv.)

Would that work?

**Comment by naztronaut** [comment]
Yeah that should work just fine. Make sure to grab your apache configuration as well. 

If you want to practice apache, flask, venv, etc, you can keep the backup handy but try setting things up from scratch. Practice makes perfect :) Just a suggestion.
